AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 with a security group that enables SSH connection.
  
Resources:
  osmanec2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-02e136e904f3da870"
      InstanceType: "t2.micro"
      KeyName: "seconkey" #please use your own key
      SecurityGroups:
        - aa.second_sec_group
      Tags:
        - Key: Name
          Value: osman-cf-stack-ec2
        - Key: Department
          Value: HR 
      UserData:  
        Fn::Base64: 
          !Sub |
            #!/bin/bash

            sudo yum update -y
            sudo yum install git -y
            sudo yum install httpd -y
            sudo yum –y install python3
            sudo yum –y install python3-pip
            sudo yum -y install python3-flask
            sudo yum -y install python-virtualenv
            sudo pip3 install flask
            cd /home/ec2-user/
            wget https://raw.githubusercontent.com/OsmanBen1681/myproject1/main/projects/project1/app.py
            mkdir static
            cd static
            wget https://github.com/OsmanBen1681/myproject1/blob/main/projects/project1/static/cat0.jpg?raw=true
            wget https://github.com/OsmanBen1681/myproject1/blob/main/projects/project1/static/cat1.jpg?raw=true
            wget https://github.com/OsmanBen1681/myproject1/blob/main/projects/project1/static/cat2.jpg?raw=true
            wget https://github.com/OsmanBen1681/myproject1/blob/main/projects/project1/static/cat3.png?raw=true
            cd ..
            mkdir templates
            cd templates
            wget https://raw.githubusercontent.com/OsmanBen1681/myproject1/main/projects/project1/templates/index.html
            cd ..
            sudo python3 app.py
            
            
          