AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloud formation for web phonebook application
Parameters:
  MyVpc:
    Description: 
    Type: AWS::EC2::VPC::Id

  MyKeyName:
    Description: 
    Type: AWS::EC2::KeyPair::KeyName
    Default: 

  MySubnets:
    Description: 
    Type: List<AWS::EC2::Subnet::Id>


  
Mappings:
  RegionImageMap:
    us-east-1:
      AMI: ami-01cc34ab2709337aa
    us-east-2:
      AMI: ami-0f19d220602031aed
    us-west-1:
      AMI: ami-0e0bf4b3a0c0e0adc
    us-west-2:
      AMI: ami-0e5b6b6a9f3db6db8
  

  
Resources:
  MyDatabaseInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      Engine: mysql
      EngineVersion: 8.0.19
      DBInstanceClass: db.t2.micro
      StorageType: "gp2"
      AllocatedStorage: "20"
      PubliclyAccessible: "true"
      BackupRetentionPeriod: 7
      DBInstanceIdentifier: !Join ["-", ["MyDatabaseInstance", !Ref "AWS::Region"]]
      MasterUsername: admin
      MasterUserPassword: johnw@1234
      DBName: phonebook
      PreferredBackupWindow: 02:00-03:00
      PreferredMaintenanceWindow: mon:03:00-mon:04:00
      VPCSecurityGroups: 
        - Fn::GetAtt: [ MyDatabaseSecurityGroup, GroupId ]
  
Transform:
  
Outputs: